@startuml

title 基于GitHub的实验管理平台--学生列表用例的顺序图

actor users

users -> 首页: 查看所有学生列表

alt 如果users是老师
    首页 -> 登录
    登录 -> 选择登录身份
	选择登录身份 -> 用户信息

else 如果users是students

    首页 -> 登录
        登录 -> 选择登录身份
    	选择登录身份 -> 用户信息

end



@enduml
